### PR TITLE
jk transform

### PR DESCRIPTION
**Pull request by squaremo**
Addresses #253.

 - [x] Add subcommand machinery
 - [x] Supply examples in help text
 - [x] Support literal JavaScript given as the script (`-c, --exec`)
 - [x] Support a file path given as the script (no flag)
 - [x] Support a module given as the script (`-m, --module`)
 - [x] Apply transform to each object in multidocs
 - [x] Balk at being expected to print to stdout if formats differ
   - [x] Happily print YAML and YAMLStream (or JSON and JSONStream) to stdout
 - ~[ ] accept input from stdin (but in which format?)~
 - [x] Write files out in output directory 
    - [x] (scheme for deciding the paths based on input paths TBD)
 - [x] --inplace (or --overwrite or whatever)
    - [x] balk if it would overwrite a file and `--overwrite` is not set

### CODE REVIEW

**Comment by squaremo** [comment]
A fun issue that has come up:

 - part of the mooted design is that `--inline` (or rather, its absence), will cause any writes that would overwrite a file to be raised as errors. Currently, there's a boolean sent in std.write to say whether an overwrite is OK; if it's false, overwrites will be _skipped_ (i.e., silently failed). One way to get to the mooted design is to have _three_ modes for dealing with (potential) overwrites -- do the overwrite, skip it, or raise an error -- and make these available in the API. *Another* way would be to keep it as a boolean, but be able to change the meaning of `false` in the runtime. The latter design may be attractive because it can then be a global flag for the runtime, something like `--overwrite=error|skip`. (Or further: remove it as an option in the lib, and _only_ control it from the runtime)

**Comment by dlespiau** [comment]
For more context, the `overwrite` fields is/was per-file because of the "node module template" use case: https://github.com/jkcfg/module-template/blob/master/module.js#L201

- if no `README` exists, create a basic one
- if a `README` already exist, don't touch it

That allows to both: bootstrap a project from scratch and get a full fledged node module ready to commit and regenerate the build files without touching certain files that may have been modified by the user.

The above seems like a nice enough use case to keep /me thinks.

**Comment by dlespiau** [comment]
This somewhat relates to not writing the files if they are identical to what already exist on the fs: https://github.com/jkcfg/jk/issues/189

**Comment by squaremo** [comment]
> regenerate the build files without touching certain files that may have been modified by the user.
> 
> The above seems like a nice enough use case to keep /me thinks.

No argument here; I was hoping to keep all use cases supported as they are now. I _think_ your use indicates a _slight_ preference for controlling the overwrite behaviour entirely from the JavaScript -- what do you reckon?

**Comment by dlespiau** [comment]
Yes, I think so too, because it has to be decided by the script author on a per-file basis (in the case of `generate`). Not sure how this would transpose to `transform` though, having a global `--in-place` seems like a good idea too.

**Comment by squaremo** [comment]
I have realised that it is odd to have `--stdout` and for the default to be `true` -- that means, whenever you want to write to files, you pass `--stdout=false`. I think it might be better to default to be consistent with generate by outputting to files unless `--stdout`; _and_ to default to raising an error before overwriting a file (ideally, before _any_ files are written).

**Comment by squaremo** [comment]
Re `--stdin`: accepting values from stdin is tricky because we don't know what format it's in. We could have `--stdin=yaml` perhaps. Rather than making a decision, I'm punting it into the future.

**Comment by squaremo** [comment]
> I think it might be better to default to be consistent with generate by outputting to files unless `--stdout`; _and_ to default to raising an error before overwriting a file (ideally, before _any_ files are written).

@dlespiau I also think that latter (raise an error rather than overwriting a file) would be a good default for `jk generate` -- I can do this in another PR, if you agree ..

**Comment by squaremo** [comment]
```
$ jk transform --help
Transform configuration files

Usage:
  jk transform <script> <file>... [flags]

Examples:

  running the default export of a module (or file) on each input document
    jk transform -o outputdir/ ./script.js ./inputdir/*.json
  running a function on each input, and printing the results to stdout
    jk transform --stdout -c '({ name: n, ...fields }) => ({ name: n + "dev", ...fields })' inputdir/*.yaml


Flags:
  -d, --emit-dependencies         emit script dependencies
  -c, --exec                      treat first argument as specifying literal JavaScript to execute
  -h, --help                      help for transform
  -i, --input-directory string    where to find files read in the script; if not set, the directory containing the script is used
  -m, --module                    treat first argument as specifying a module to load
  -o, --output-directory string   where to output generated files
      --overwrite                 allow input file(s) to be overwritten by output file(s); otherwise, an error will be thrown
  -p, --parameter name=value      set input parameters
  -f, --parameters filename       load parameters from a JSON or YAML file
      --stdout                    print the resulting values to stdout
  -v, --verbose                   verbose output
```

Wrinkle: `--input-directory` is a global flag, but doesn't have an interpretation here (because the individual files are named explicitly as arguments).

**Comment by dlespiau** [comment]
oooh, exciting, can't wait to play with it!

**Pull request merged**
