### PR TITLE
fix run-in-docker instructions

### PR DESCRIPTION
**Pull request by bryanlarsen**

### CODE REVIEW

**Comment by bryanlarsen** [comment]
Yah, it turns out both of our instructions are broken.

So I first did "make" and I got this error:

```
std/generate.sh
cd std && npm run build

> std@0.1.0 build /go/src/github.com/jkcfg/jk/std
> mkdir -p build && rollup -c > build/std.js | terser --compress defaults=false,dead_code --module | prettier --stdin-filepath std.js > build/std.js

sh: 1: rollup: not found
sh: 1: terser: not found
sh: 1: prettier: not found
```

So I then did 'make jk' and it appeared to work.   But the resulting jk didn't have 'std' built in, unsurprisingly.

**Comment by bryanlarsen** [comment]
I got it to work by running `make dep` outside of docker, ignoring the error about missing go and then running `make` inside docker.   But I did have node & npm installed.

**Comment by dlespiau** [comment]
Ah, ah! that makes sense now. Indeed you need make dep first to retrieve the node modules we need to build the js part of the std library. For instance CI has:

```
        - ./run-in-docker.sh make dep install test
```

I forgot the `dep` step because I have my `node_modules` directory already.

So I think changing the instructions to:

```
        - ./run-in-docker.sh make dep jk
```

would do the trick!

**Comment by bryanlarsen** [comment]
indeed it does! updated.

**Comment by dlespiau** [comment]
`quay.io is [having an outage](http://status.quay.io/) at the moment:

```
docker: Error response from daemon: Get https://quay.io/v2/: EOF.
```

Re-started the run.

**Comment by dlespiau** [comment]
Given we're just changing a markdown file here. Going to merge! thanks a lot for your first contribution! :)

**Pull request merged**
